spring:


  datasource:
    url: jdbc:mysql://localhost:3306/smallshop?user=root&password=12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    encoding: utf-8
    mode: HTML5
    cache: false

  jpa:
    generate-ddl: true
    hibernate:
       ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB
      file-size-threshold: 2KB



server:
  port: 9090